name: Docker Build & Push

on:
  push:
    tags:
      - "*"
  schedule:
    - cron: "30 10 * * 4"
  workflow_dispatch:
    inputs:
      force:
        description: Build the image even if it already exists
        required: false
        default: false
        type: boolean

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      TARGET_IMAGE_TAG: ${{ steps.caddy-version.outputs.release }}
      CADDY_VERSION: ${{ steps.prepare.outputs.caddy-version }}
    steps:
      - name: Get latest Caddy version
        id: caddy-version
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          owner: caddyserver
          repo: caddy
          token: ${{ secrets.GITHUB_TOKEN }}
          excludes: prerelease, draft

      - name: Prepare
        id: prepare
        run: echo "caddy-version=$(echo "${{ steps.caddy-version.outputs.release }}"|awk '{print substr($0, 2)}')" >> $GITHUB_OUTPUT

  build:
    needs: initialize
    uses: aszili/github-actions/.github/workflows/build-docker-image.yml@main
    with:
      target_tag: ${{ needs.initialize.outputs.TARGET_IMAGE_TAG }}
      build_args: CADDY_VERSION=${{ needs.initialize.outputs.CADDY_VERSION }}
      force: ${{ false || inputs.force}}